prefix = "testlinux"
location = "northeurope"
resource_group_name = "rg-k8"
subnet = "/subscriptions/bf3302fc-520e-4bde-8832-8cf0f1ce216c/resourceGroups/rg-k8/providers/Microsoft.Network/virtualNetworks/rg-k8-vnet/subnets/default"
username = "amolw"
password = "Amolw!@#"